add_subdirectory(RecDCHDedx)
add_subdirectory(RecPFAArbor)
add_subdirectory(RecPFACyber)
# add_subdirectory(RecPFAPandora)
add_subdirectory(RecSiTracking)
add_subdirectory(RecTrkGlobal)
add_subdirectory(RecDCHGenfit)
add_subdirectory(RecAssociationMaker)
add_subdirectory(ParticleID)
# add_subdirectory(RecActsTracking)
